# Independent USB/BLE host: no split central/peripheral transport.
CONFIG_ZMK_SPLIT=n
CONFIG_ZMK_BLE=y
CONFIG_ZMK_USB=y
CONFIG_ZMK_BATTERY_REPORTING=y
CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n
CONFIG_RGBLED_WIDGET_SHOW_LAYER_CHANGE=y
